//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WizardWrx.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WizardWrx.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carat (^, ASCII code 0x5E).
        /// </summary>
        internal static string DLM_DSP_CARAT {
            get {
                return ResourceManager.GetString("DLM_DSP_CARAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carriage return (CR, ASCII code 0x0D).
        /// </summary>
        internal static string DLM_DSP_CARRIAGE_RETURN {
            get {
                return ResourceManager.GetString("DLM_DSP_CARRIAGE_RETURN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comma (, ASCII code 0x2C).
        /// </summary>
        internal static string DLM_DSP_COMMA {
            get {
                return ResourceManager.GetString("DLM_DSP_COMMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line feed (LF, ASCII code 0x0A).
        /// </summary>
        internal static string DLM_DSP_LINE_FEED {
            get {
                return ResourceManager.GetString("DLM_DSP_LINE_FEED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other ({0}, ASCII code {1}).
        /// </summary>
        internal static string DLM_DSP_OTHER {
            get {
                return ResourceManager.GetString("DLM_DSP_OTHER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space (ASCII code 0x20).
        /// </summary>
        internal static string DLM_DSP_SPACE {
            get {
                return ResourceManager.GetString("DLM_DSP_SPACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tab (Horizontal Tab, ASCII code 0x09).
        /// </summary>
        internal static string DLM_DSP_TAB {
            get {
                return ResourceManager.GetString("DLM_DSP_TAB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical Bar (|,  a. k. a. Pipe, ASCII code 0x7C).
        /// </summary>
        internal static string DLM_DSP_VERTICAL_BAR {
            get {
                return ResourceManager.GetString("DLM_DSP_VERTICAL_BAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The delimiter and guard characters must differ.{2}    Specified Delimiter Character = {0}{2}    Specified Guard Character     = {1}.
        /// </summary>
        internal static string ERRMSG_SAME_CHAR_AS_DLM_AND_GUARD {
            get {
                return ResourceManager.GetString("ERRMSG_SAME_CHAR_AS_DLM_AND_GUARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings on this instance are locked..
        /// </summary>
        internal static string ERRMSG_SETTINGS_ARE_LOCKED {
            get {
                return ResourceManager.GetString("ERRMSG_SETTINGS_ARE_LOCKED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is of type {1}, which cannot be meaningfully compared to a {2}, which is of type {3}..
        /// </summary>
        internal static string ERRMSG_TYPE_MISMATCH {
            get {
                return ResourceManager.GetString("ERRMSG_TYPE_MISMATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back Quotation Mark (`, ASCII code 0x60).
        /// </summary>
        internal static string GRD_DSP_BACK_QUOTE {
            get {
                return ResourceManager.GetString("GRD_DSP_BACK_QUOTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double Quotation Mark (&quot;, ASCII code 0x22).
        /// </summary>
        internal static string GRD_DSP_DOUBLE_QUOTE {
            get {
                return ResourceManager.GetString("GRD_DSP_DOUBLE_QUOTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single Quotation Mark (&apos;, ASCII code 0x27).
        /// </summary>
        internal static string GRD_DSP_SINGLE_QUOTE {
            get {
                return ResourceManager.GetString("GRD_DSP_SINGLE_QUOTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0},{1},{2},{3},{4},{5}.
        /// </summary>
        internal static string HASH_CODE_TEMPLATE {
            get {
                return ResourceManager.GetString("HASH_CODE_TEMPLATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delimiter         = {0}{6}Guard Character   = {1}{6}Trim White Space  = {2}{6}Guard Disposition = {3}{6}Lock State        = {4}{6}Lock Method       = {5}{6}.
        /// </summary>
        internal static string TOSTRING_TEMPLATE {
            get {
                return ResourceManager.GetString("TOSTRING_TEMPLATE", resourceCulture);
            }
        }
    }
}
