// Generated .IDL file (by the OLE/COM Object Viewer)
// 
// typelib filename: WizardWrx.AnyCSV.tlb

[
  uuid(24256A33-D92A-4883-8C41-2D69FFEBC6E5),
  version(4.0),
  helpstring("AnyCSV - Process ANY delimited string."),
  custom(90883F05-3D28-11D2-8F17-00A0C9A6186D, "WizardWrx.AnyCSV, Version=4.0.83.23199, Culture=neutral, PublicKeyToken=null")

]
library WizardWrx_AnyCSV
{
    // TLib :     // TLib : mscorlib.dll : {BED7F4EA-1A96-11D2-8F08-00A0C9A6186D}
    importlib("mscorlib.tlb");
    // TLib : OLE Automation : {00020430-0000-0000-C000-000000000046}
    importlib("stdole2.tlb");

    // Forward declare all types defined in this typelib
    interface _RobustDelimitedStringParser;

    typedef [uuid(EBC3549F-FE2A-4CB1-9006-0F48427F2A7A), version(1.0)    ,
      custom(0F21F359-AB84-41E8-9A78-36D110E6D2F9, "WizardWrx.AnyCSV.CSVParseEngine+DelimiterChar")    
]
    enum {
        DelimiterChar_None = 0,
        DelimiterChar_Carat = 1,
        DelimiterChar_CarriageReturn = 2,
        DelimiterChar_Comma = 3,
        DelimiterChar_LineFeed = 4,
        DelimiterChar_Space = 5,
        DelimiterChar_Tab = 6,
        DelimiterChar_VerticalBar = 7,
        DelimiterChar_Other = 8
    } DelimiterChar;

    typedef [uuid(A9271285-A237-4778-924F-4D0FA90F9604), version(1.0)    ,
      custom(0F21F359-AB84-41E8-9A78-36D110E6D2F9, "WizardWrx.AnyCSV.CSVParseEngine+GuardChar")    
]
    enum {
        GuardChar_None = 0,
        GuardChar_BackQuote = 1,
        GuardChar_DoubleQuote = 2,
        GuardChar_SingleQuote = 3,
        GuardChar_Other = 4
    } GuardChar;

    typedef [uuid(71CCEE5A-CF43-43B2-A6C8-F219EEC9E30F), version(1.0)    ,
      custom(0F21F359-AB84-41E8-9A78-36D110E6D2F9, "WizardWrx.AnyCSV.CSVParseEngine+GuardDisposition")    
]
    enum {
        GuardDisposition_Keep = 0,
        GuardDisposition_Strip = 1
    } GuardDisposition;

    typedef [uuid(8F92D749-FD8E-4573-8D5B-5997280B370A), version(1.0)    ,
      custom(0F21F359-AB84-41E8-9A78-36D110E6D2F9, "WizardWrx.AnyCSV.CSVParseEngine+LockMethod")    
]
    enum {
        LockMethod_IsUnlocked = 0,
        LockMethod_LockedExplicitly = 1,
        LockMethod_LockedImplicitly = 2
    } LockMethod;

    typedef [uuid(31C2E565-76BB-4DCE-9648-530B5C83CECA), version(1.0)    ,
      custom(0F21F359-AB84-41E8-9A78-36D110E6D2F9, "WizardWrx.AnyCSV.CSVParseEngine+LockState")    
]
    enum {
        LockState_Unlocked = 0,
        LockState_Locked = 1
    } LockState;

    typedef [uuid(093B06A4-2450-430E-8E67-0D988638FE2A), version(1.0)    ,
      custom(0F21F359-AB84-41E8-9A78-36D110E6D2F9, "WizardWrx.AnyCSV.CSVParseEngine+TrimWhiteSpace")    
]
    enum {
        TrimWhiteSpace_Leave = 0,
        TrimWhiteSpace_TrimLeading = 1,
        TrimWhiteSpace_TrimTrailing = 2,
        TrimWhiteSpace_TrimBoth = 3
    } TrimWhiteSpace;

    [
      uuid(EE63E545-0FC1-42F0-9DDD-028A5FFD438F),
      version(1.0),
      custom(0F21F359-AB84-41E8-9A78-36D110E6D2F9, "WizardWrx.AnyCSV.RobustDelimitedStringParser")
    ]
    coclass RobustDelimitedStringParser {
        [default] interface _RobustDelimitedStringParser;
        interface _Object;
    };

    [
      odl,
      uuid(A8F2848B-9A12-36CB-8141-B53CCF411537),
      hidden,
      dual,
      nonextensible,
      oleautomation,
      custom(0F21F359-AB84-41E8-9A78-36D110E6D2F9, "WizardWrx.AnyCSV.RobustDelimitedStringParser")    

    ]
    interface _RobustDelimitedStringParser : IDispatch {
        [restricted] void Missing7();
        [restricted] void Missing8();
        [restricted] void Missing9();
        [id(0x60020003)]
        HRESULT GetType([out, retval] _Type** pRetVal);
        [id(0x60020004), propget]
        HRESULT FieldDelimiter([out, retval] unsigned short* pRetVal);
        [id(0x60020004), propput]
        HRESULT FieldDelimiter([in] unsigned short pRetVal);
        [id(0x60020006), propget]
        HRESULT DelimiterGuard([out, retval] unsigned short* pRetVal);
        [id(0x60020006), propput]
        HRESULT DelimiterGuard([in] unsigned short pRetVal);
        [id(0x60020008), propget]
        HRESULT GuardCharDisposition([out, retval] GuardDisposition* pRetVal);
        [id(0x60020008), propput]
        HRESULT GuardCharDisposition([in] GuardDisposition pRetVal);
        [id(0x6002000a), propget]
        HRESULT WhiteSpaceDisposition([out, retval] TrimWhiteSpace* pRetVal);
        [id(0x6002000a), propput]
        HRESULT WhiteSpaceDisposition([in] TrimWhiteSpace pRetVal);
        [id(0x6002000c), propget]
        HRESULT SettingsLocked([out, retval] LockState* pRetVal);
        [id(0x6002000d)]
        HRESULT LockSettings();
        [id(0x6002000e)]
        HRESULT Parse(
                        [in] BSTR pstrAnyCSV, 
                        [out, retval] SAFEARRAY(BSTR)* pRetVal);
    };
};
